# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI=4

MODULE_AUTHOR="FLORA"
MODULE_VERSION="0.05"

inherit perl-module

DESCRIPTION="Perl interface to libnotify"

LICENSE="|| ( GPL-2 LGPL-2 )"
SLOT="0"
KEYWORDS="~x86 ~amd64"
IUSE=""

PATCHES=( "${FILESDIR}"/${P}-libnotify-0.7.patch )

RDEPEND="
	dev-lang/perl
	dev-perl/glib-perl
	dev-perl/gtk2-perl
"
DEPEND="$RDEPEND
	dev-perl/extutils-depends
	dev-perl/extutils-pkgconfig
"
TDEPEND="dev-perl/Test-Exception"
